<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\CD-1.ico</ApplicationIcon>
    <Version>2.0.0.0</Version>
    <Company>Ixar</Company>
    <Copyright>Ixar</Copyright>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
  </PropertyGroup>

  <ItemGroup>
	  <Resource Include="Assets\**\*.*">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\CD-1.ico" />
    <Content Include="Browser\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Taunts\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\ransom_idle.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\ransom_attack.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\repent.gif" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\thx_txt.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="3.0.1" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
  </ItemGroup>

</Project>
